### PR TITLE
[WIP] Print multiline log messages correctly

### PR DESCRIPTION
**Pull request by FliegendeWurst**
See issue #3. One of these formats should be selected (by the user perhaps?) (last option is currently implemented):
```
INFO [src/main.rs:5] aaa
                     bbb
                     ccc
INFO [src/main.rs:5] aaa
bbb
ccc
INFO [src/main.rs:5]
aaa
bbb
ccc
```
Another issue is that it now prints way too many log messages if there are multiline messages (see first TODO in the code).

### CODE REVIEW

**Comment by fia0** [comment]
Hi FliegendeWurst, thank you for your PR!
From the formats you propose I suggest we implement the first one as this generally preserves the best readability for the reader. Similar to how `journalctl` displays log messages for orientation. But i'm open for discussion.
FlexiLogger implements suggestion no.2, but personally I would tend to one of the other proposed here.

As for patches in cursive - Yes totally propose this to gyscos, and you can get it merged quite quickly, but it may take some time to get it released. We should add a workaround for now to not depend on it to release.

@fin-ger What do you think?

**Comment by fin-ger** [comment]
Personally, I think a continuation sequence helps in readability. However, being compatible (and consistent) with flexi-logger is more important than trying to do it "better".

Nevertheless, these are the ideas that came to my mind:

scala-like
```
INFO [src/main.rs:5] aaa
                   | bbb
                   | ccc
```

pythonic
```
INFO [src/main.rs:5] aaa
                 ... bbb
                 ... ccc
```

gentoo-like
```
INFO [src/main.rs:5] aaa
                 >>> bbb
                 >>> ccc
```

**Comment by FliegendeWurst** [comment]
> From the formats you propose I suggest we implement the first one as this generally preserves the best readability for the reader. Similar to how `journalctl` displays log messages for orientation. But i'm open for discussion.
> FlexiLogger implements suggestion no.2, but personally I would tend to one of the other proposed here.

I implemented the third format because the log messages also contained relatively long lines (making it necessary to scroll past 20-100 blank characters).

**Comment by FliegendeWurst** [comment]
Closing this because format 1 is implemented in PR #6.

**Pull request closed without merging**
